version: '3.8'

services:
  webapp:
    build:
      context: ./nextjs-webapp
    ports:
      - "3000:3000"
    volumes:
      # Mount host Nginx logs (read-only) into the container
      # IMPORTANT: Ensure 'C:/nginx/logs' is the correct path on your HOST system
      - type: bind
        source: C:/nginx/logs  # Path on your Windows host
        target: /var/log/nginx_host # Path inside the container
        read_only: true

# networks:
#   shieldnet:
#     driver: bridge

networks:
  shieldnet:
    driver: bridge
