version: '3.8'

services:
  nginx-shield:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapp
    networks:
      - shieldnet
    volumes:
      - ./nginx_logs:/var/log/nginx  # Mounting local 'nginx_logs' directory to container's log directory

  webapp:
    build:
      context: ./nextjs-webapp # Point to the Next.js app directory
    # No ports needed here, accessed internally by nginx-shield
    networks:
      - shieldnet

networks:
  shieldnet:
    driver: bridge
