version: '3.8'

services:
  nginx-shield:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapp
    networks:
      - shieldnet
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx_config/blocked_ips.conf:/etc/nginx/conf.d/blocked_ips.conf:rw
      - ./nginx_logs:/var/log/nginx:rw

  webapp:
    build:
      context: ./nextjs-webapp
    networks:
      - shieldnet

networks:
  shieldnet:
    driver: bridge
